# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'linters/sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: '/**/*.s+(a|c)ss'
  ignore:
    - '(sass|scss)/vendor/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  no-empty-rulesets: 2
  no-trailing-whitespace: 2
  final-newline: 2
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 1
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 4
  property-sort-order:
    - 1
    -
      order:
        - box-shadow
        - background
        - background-color
        - color
        - font
        - font-size
        - line-height
        - position
        - display
        - padding
        - border
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 2
    -
      properties:
        - color
        - background-color
  bem-depth:
    - 2
    -
      max-depth: 1
  border-zero:
    - 2
    -
      convention: '0'
